/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Resource = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'resourceType' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'resources' : IDL.Vec(Resource),
  'description' : IDL.Text,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'chapters' : IDL.Vec(Chapter),
});

export const idlService = IDL.Service({
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCourseById' : IDL.Func([IDL.Nat], [Course], ['query']),
  'initialize' : IDL.Func([], [IDL.Bool], []),
  'searchCoursesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'searchLessonsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Resource = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'resourceType' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'resources' : IDL.Vec(Resource),
    'description' : IDL.Text,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'chapters' : IDL.Vec(Chapter),
  });
  
  return IDL.Service({
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCourseById' : IDL.Func([IDL.Nat], [Course], ['query']),
    'initialize' : IDL.Func([], [IDL.Bool], []),
    'searchCoursesBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'searchLessonsByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Lesson)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };